apiVersion: v1
kind: Service
metadata:
  name: nest
  labels:
    app: nest
spec:
  selector:
    app: nest
  ports:
    - name: nest-http
      protocol: TCP
      port: 80
    - name: nest-ws
      protocol: TCP
      port: 81