version: "3.7"
services:
  keycloak:
    image: quay.io/keycloak/keycloak:16.1.1
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      KEYCLOAK_IMPORT: /tmp/rendezvous.json
      JAVA_OPTS_APPEND: "-Dkeycloak.profile.feature.upload_scripts=enabled"
    volumes:
      - "./rendezvous.json:/tmp/rendezvous.json"
