name: Build and Deploy
on: [ push ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install and Build 🔧
        uses: actions/setup-node@v2
        with:
          node-version: '12'
          cache: 'npm'
        run: |
          yarn install
          yarn run build:prod

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: master
          folder: build
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          repository-name: ilinaraducristian/ilinaraducristian.github.io